### ISSUE TITLE
Write staging url to PullRequest automaticaly

### ISSUE THREAD

**Issue by chaspy** [chaspy/favsearch#34]
to access easily

ex: http://favsearch-pr-99.herokuapp.com

**Comment by chaspy** [comment]
📝 
I want to make it more versatile. I'd like the user who cooperates with github to use the reviewapp of heroku.

- Be a simple execution command
- Just pick up the heroku's `app_name` and the number of the pull request
- Only when the pull-request is open (notification only once)
   - It is good to pick up the action of pull-request, but if you incorporate it into CI ...
   - GitHub App ??

**Comment by kamontia** [comment]
@chaspy Is this issue the development of GithubApp that posts the staging URL when PR is opened, isn't it? Unnecessary to develop it because a button to lead staging environment is added automatically.
Push `view deployment` button, you can access staging environment.
![2018-10-29-120408_1785x857_scrot](https://user-images.githubusercontent.com/17017563/47627436-5e9efd80-db73-11e8-83f9-c080aa7db830.png)

**Comment by chaspy** [comment]
💥 
awesome!!!!!!!!!!!!!!!! I didn't know!!!!!!!!!!!
